# Generated by Django 3.1.6 on 2021-02-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBabe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('site', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('gallery', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('file', models.ImageField(upload_to='pics')),
                ('tn', models.ImageField(upload_to='pics')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('pob', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('occ', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'atk_allsites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Babe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gallery', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('pob', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('occ', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('file', models.ImageField(upload_to='pics')),
                ('tn', models.ImageField(upload_to='pics')),
                ('tags', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vote', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteBabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('site', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sitebabe',
            constraint=models.UniqueConstraint(fields=('date', 'name', 'site'), name='unique_sitebabe'),
        ),
    ]
