# Generated by Django 3.1.6 on 2021-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('votemonth', models.IntegerField()),
                ('vote', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
    ]
