# Generated by Django 3.1.6 on 2021-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0002_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='votemonth',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
