# Generated by Django 3.1.6 on 2021-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0003_auto_20210202_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('votemonth', models.IntegerField(blank=True, default=None, null=True)),
                ('vote', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
    ]
