# Generated by Django 3.1.6 on 2021-02-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0004_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duel',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
