# Generated by Django 3.1.6 on 2021-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0005_auto_20210202_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babe',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
