# Generated by Django 3.1.6 on 2021-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0006_auto_20210208_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'atk_novote',
                'managed': False,
            },
        ),
    ]
