# Generated by Django 3.1.6 on 2021-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0007_novote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='second',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
