# Generated by Django 3.1.6 on 2021-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0008_auto_20210210_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('c', models.IntegerField()),
                ('s', models.IntegerField()),
                ('vote', models.IntegerField()),
            ],
            options={
                'db_table': 'best_score',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='babe',
            name='duellikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='babe',
            name='monthlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='babe',
            name='oldlikes',
            field=models.IntegerField(default=0),
        ),
    ]
