# Generated by Django 3.1.6 on 2021-02-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0009_auto_20210220_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebabe',
            name='duellikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitebabe',
            name='monthlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitebabe',
            name='oldlikes',
            field=models.IntegerField(default=0),
        ),
    ]
