# Generated by Django 3.1.6 on 2021-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0010_auto_20210220_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babe',
            name='monthlikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
