# Generated by Django 3.1.6 on 2021-02-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0011_auto_20210221_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babe',
            name='monthlikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
