# Generated by Django 3.1.6 on 2021-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0012_auto_20210221_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babe',
            name='oldlikes',
        ),
        migrations.RemoveField(
            model_name='sitebabe',
            name='oldlikes',
        ),
        migrations.AlterField(
            model_name='babe',
            name='monthlikes',
            field=models.IntegerField(default=0),
        ),
    ]
