# Generated by Django 3.1.6 on 2021-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0013_auto_20210221_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('urls', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
